-- MySQL Script generated by MySQL Workbench
-- Sun May 10 17:21:48 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema animalitos_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema animalitos_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `animalitos_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `animalitos_db` ;

-- -----------------------------------------------------
-- Table `animalitos_db`.`animales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`animales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `url_imagen` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE,
  UNIQUE INDEX `url_imagen_UNIQUE` (`url_imagen` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `animalitos_db`.`estados_apuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`estados_apuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `animalitos_db`.`sorteos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`sorteos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora_revelacion` TIME NOT NULL,
  `esta_activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `animalitos_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `animalitos_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(32) NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  `saldo_retenido` DECIMAL(10,2) NOT NULL,
  `numero_documento` VARCHAR(15) NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  INDEX `fk_usuarios_roles1_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `animalitos_db`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `animalitos_db`.`apuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`apuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  `usuario_id` INT NOT NULL,
  `sorteo_id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  `animal_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_apuestas_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_apuestas_sorteos1_idx` (`sorteo_id` ASC) VISIBLE,
  INDEX `fk_apuestas_estados_apuestas1_idx` (`estado_id` ASC) VISIBLE,
  INDEX `fk_apuestas_animales1_idx` (`animal_id` ASC) VISIBLE,
  CONSTRAINT `fk_apuestas_animales1`
    FOREIGN KEY (`animal_id`)
    REFERENCES `animalitos_db`.`animales` (`id`),
  CONSTRAINT `fk_apuestas_estados_apuestas1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `animalitos_db`.`estados_apuestas` (`id`),
  CONSTRAINT `fk_apuestas_sorteos1`
    FOREIGN KEY (`sorteo_id`)
    REFERENCES `animalitos_db`.`sorteos` (`id`),
  CONSTRAINT `fk_apuestas_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `animalitos_db`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `animalitos_db`.`pasarelas_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`pasarelas_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `url` VARCHAR(300) NOT NULL,
  `url_imagen` VARCHAR(300) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `animalitos_db`.`premios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`premios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(10,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `apuesta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_pagos_apuestas1_idx` (`apuesta_id` ASC) VISIBLE,
  CONSTRAINT `fk_pagos_apuestas1`
    FOREIGN KEY (`apuesta_id`)
    REFERENCES `animalitos_db`.`apuestas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `animalitos_db`.`recargas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`recargas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(10,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `pasarela_pago_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_recargas_metodos_pago1_idx` (`pasarela_pago_id` ASC) VISIBLE,
  INDEX `fk_recargas_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_recargas_metodos_pago1`
    FOREIGN KEY (`pasarela_pago_id`)
    REFERENCES `animalitos_db`.`pasarelas_pago` (`id`),
  CONSTRAINT `fk_recargas_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `animalitos_db`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `animalitos_db`.`resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`resultados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sorteo_id` INT NOT NULL,
  `animal_ganador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_resultados_sorteos1_idx` (`sorteo_id` ASC) VISIBLE,
  INDEX `fk_resultados_animales1_idx` (`animal_ganador_id` ASC) VISIBLE,
  CONSTRAINT `fk_resultados_animales1`
    FOREIGN KEY (`animal_ganador_id`)
    REFERENCES `animalitos_db`.`animales` (`id`),
  CONSTRAINT `fk_resultados_sorteos1`
    FOREIGN KEY (`sorteo_id`)
    REFERENCES `animalitos_db`.`sorteos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `animalitos_db`.`tipos_metodos_retiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`tipos_metodos_retiro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animalitos_db`.`estados_retiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`estados_retiro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripion` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animalitos_db`.`metodos_retiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`metodos_retiro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `url_imagen` VARCHAR(300) NULL,
  `monto_minimo` DECIMAL(10,2) NOT NULL,
  `monto_maximo` DECIMAL(10,2) NULL,
  `comision_fija` DECIMAL(10,2) NOT NULL,
  `comision_porcentual` INT NOT NULL,
  `esta_activo` TINYINT(1) NOT NULL,
  `tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_metodos_retiro_tipos_metodos_retiro1_idx` (`tipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_metodos_retiro_tipos_metodos_retiro1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `animalitos_db`.`tipos_metodos_retiro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animalitos_db`.`cuentas_retiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`cuentas_retiro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_titular` VARCHAR(150) NOT NULL,
  `numero_cuenta` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `fecha_registro` DATE NOT NULL,
  `metodo_retiro_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cuentas_retiro_metodos_retiro1_idx` (`metodo_retiro_id` ASC) VISIBLE,
  INDEX `fk_cuentas_retiro_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_cuentas_retiro_metodos_retiro1`
    FOREIGN KEY (`metodo_retiro_id`)
    REFERENCES `animalitos_db`.`metodos_retiro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuentas_retiro_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `animalitos_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animalitos_db`.`retiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animalitos_db`.`retiros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(10,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `estado_id` INT NOT NULL,
  `cuenta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_retiros_estados_retiro1_idx` (`estado_id` ASC) VISIBLE,
  INDEX `fk_retiros_cuentas_retiro1_idx` (`cuenta_id` ASC) VISIBLE,
  CONSTRAINT `fk_retiros_estados_retiro1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `animalitos_db`.`estados_retiro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_retiros_cuentas_retiro1`
    FOREIGN KEY (`cuenta_id`)
    REFERENCES `animalitos_db`.`cuentas_retiro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
